[package]
name = "ebpf-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.8"
generate = {path = "../generate", version = "1.0.0"}
monitor = {path = "../monitor", version = "1.0.0"}